/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    chatas: Chata;
    participants: Participant;
    expenses: Expense;
    prepayments: Prepayment;
    backgrounds: Background;
    icons: Icon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    chatas: ChatasSelect<false> | ChatasSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    prepayments: PrepaymentsSelect<false> | PrepaymentsSelect<true>;
    backgrounds: BackgroundsSelect<false> | BackgroundsSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins can manage all chatas, users can only manage assigned chatas
   */
  role: 'admin' | 'user';
  /**
   * Chatas this user can manage (only applies to non-admin users)
   */
  assignedChatas?: (number | Chata)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatas".
 */
export interface Chata {
  id: number;
  /**
   * Full name of the chata/trip (e.g., "Chaloupka pod Medem")
   */
  name: string;
  /**
   * Short name used in QR codes and messages (e.g., "Chaloupka")
   */
  shortName: string;
  /**
   * Location description (e.g., "Beskydy")
   */
  location: string;
  /**
   * URL-friendly identifier for this chata
   */
  slug: string;
  /**
   * Domain names that should automatically load this chata
   */
  domains?:
    | {
        /**
         * Domain hostname (e.g., "chata.zicha.name")
         */
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Person managing the money for this trip
   */
  banker?: (number | null) | Participant;
  /**
   * Banker's account number in Czech format (e.g., "123456/0100")
   */
  bankerAccountNumber: string;
  /**
   * Banker's IBAN for QR code generation
   */
  bankerIban: string;
  /**
   * Users who can manage this chata
   */
  assignedUsers?:
    | {
        user: number | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Background image (uses system default if not set)
   */
  background?: (number | null) | Background;
  /**
   * Icon (uses cottage icon if not set)
   */
  icon?: (number | null) | Icon;
  /**
   * Theme color (hex)
   */
  themeColor?: string | null;
  /**
   * Enable the information/details view for this trip
   */
  informationEnabled?: boolean | null;
  tripDateFrom?: string | null;
  tripDateTo?: string | null;
  /**
   * Name of the accommodation (e.g., "Chaloupka pod Medem")
   */
  destinationName?: string | null;
  /**
   * Specific location (e.g., "Horní Lomná")
   */
  destinationLocation?: string | null;
  /**
   * Description of the destination
   */
  destinationDescription?: string | null;
  /**
   * Useful links about the destination
   */
  destinationLinks?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Photos of the destination
   */
  photos?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Basic information bullets
   */
  basicInfo?:
    | {
        info: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Parking information
   */
  parking?: string | null;
  /**
   * Driving directions
   */
  carRoutes?:
    | {
        from: string;
        /**
         * e.g., "3:30"
         */
        duration: string;
        /**
         * e.g., "300 km"
         */
        distance: string;
        /**
         * Route description
         */
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public transport options
   */
  publicTransportOptions?:
    | {
        /**
         * e.g., "Z Prahy"
         */
        title: string;
        /**
         * Total journey time
         */
        totalDuration?: string | null;
        /**
         * Additional notes
         */
        notes?: string | null;
        connections?:
          | {
              type: 'vlak' | 'autobus';
              /**
               * Train/bus number
               */
              number: string;
              from: string;
              to: string;
              /**
               * Format: HH:MM (e.g., "08:45")
               */
              departure: string;
              /**
               * Format: HH:MM (e.g., "12:30")
               */
              arrival: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable the bedroom organization view for this trip
   */
  bedroomOrganizationEnabled?: boolean | null;
  /**
   * Enable per-night occupancy tracking (requires trip dates)
   */
  advancedBedroomMode?: boolean | null;
  /**
   * Rooms available at this accommodation
   */
  rooms?:
    | {
        /**
         * Room name (e.g., "Pokoj u krbu", "Podkroví")
         */
        name: string;
        /**
         * Optional description of the room
         */
        description?: string | null;
        /**
         * Photo of the room
         */
        image?: (number | null) | Media;
        /**
         * Maximum number of people who can sleep in this room
         */
        maxSleepingSpaces: number;
        /**
         * Beds in this room
         */
        beds?:
          | {
              /**
               * Bed name/type (e.g., "Manželská postel", "Palanda - horní")
               */
              name: string;
              /**
               * Who sleeps in this bed
               */
              occupants?:
                | {
                    participant: number | Participant;
                    /**
                     * Which nights (1-indexed). Empty = all nights. E.g. [1, 2, 3]
                     */
                    nights?:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  /**
   * Participant's full name
   */
  name: string;
  /**
   * The trip/chata this participant belongs to
   */
  chata: number | Chata;
  /**
   * Account number in Czech format (e.g., "123456/0100") - only needed for creditors
   */
  accountNumber?: string | null;
  /**
   * Full IBAN for QR code generation - only needed for creditors
   */
  iban?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backgrounds".
 */
export interface Background {
  id: number;
  /**
   * Display name for this background
   */
  name: string;
  /**
   * System default - cannot be deleted
   */
  isDefault?: boolean | null;
  type: 'url' | 'upload';
  /**
   * External image URL (e.g., Unsplash)
   */
  url?: string | null;
  /**
   * Upload a background image
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  /**
   * Display name for this icon
   */
  name: string;
  /**
   * System default - cannot be deleted
   */
  isDefault?: boolean | null;
  /**
   * Upload an SVG icon file
   */
  svg: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  /**
   * The trip/chata this expense belongs to
   */
  chata: number | Chata;
  /**
   * Description of the expense
   */
  title: string;
  /**
   * Total amount (use negative values for refunds)
   */
  amount: number;
  /**
   * Who paid for this expense
   */
  payer: number | Participant;
  /**
   * How to split this expense among participants
   */
  splitType: 'equal' | 'weighted';
  /**
   * Weighted distribution - only used when Split Type is "Weighted"
   */
  weights?:
    | {
        /**
         * Participant sharing this expense
         */
        participant: number | Participant;
        /**
         * Weight multiplier for this participant (e.g., 1, 0.5, 2)
         */
        weight: number;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  /**
   * Optional notes about this expense
   */
  note?: string | null;
  /**
   * Planned expense (not yet paid) - uncheck when actually paid
   */
  isPlanned?: boolean | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prepayments".
 */
export interface Prepayment {
  id: number;
  /**
   * The trip/chata this prepayment belongs to
   */
  chata: number | Chata;
  /**
   * Who sent the payment (or who received it if negative)
   */
  from: number | Participant;
  /**
   * Amount (positive = to banker, negative = from banker/refund)
   */
  amount: number;
  /**
   * Description (e.g., "Záloha", "Doplatek", "Distribuce")
   */
  note?: string | null;
  /**
   * Type of prepayment
   */
  type: 'advance' | 'supplement' | 'refund' | 'distribution';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'chatas';
        value: number | Chata;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'prepayments';
        value: number | Prepayment;
      } | null)
    | ({
        relationTo: 'backgrounds';
        value: number | Background;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  assignedChatas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatas_select".
 */
export interface ChatasSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  location?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  banker?: T;
  bankerAccountNumber?: T;
  bankerIban?: T;
  assignedUsers?:
    | T
    | {
        user?: T;
        id?: T;
      };
  background?: T;
  icon?: T;
  themeColor?: T;
  informationEnabled?: T;
  tripDateFrom?: T;
  tripDateTo?: T;
  destinationName?: T;
  destinationLocation?: T;
  destinationDescription?: T;
  destinationLinks?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  basicInfo?:
    | T
    | {
        info?: T;
        id?: T;
      };
  parking?: T;
  carRoutes?:
    | T
    | {
        from?: T;
        duration?: T;
        distance?: T;
        route?: T;
        id?: T;
      };
  publicTransportOptions?:
    | T
    | {
        title?: T;
        totalDuration?: T;
        notes?: T;
        connections?:
          | T
          | {
              type?: T;
              number?: T;
              from?: T;
              to?: T;
              departure?: T;
              arrival?: T;
              id?: T;
            };
        id?: T;
      };
  bedroomOrganizationEnabled?: T;
  advancedBedroomMode?: T;
  rooms?:
    | T
    | {
        name?: T;
        description?: T;
        image?: T;
        maxSleepingSpaces?: T;
        beds?:
          | T
          | {
              name?: T;
              occupants?:
                | T
                | {
                    participant?: T;
                    nights?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  chata?: T;
  accountNumber?: T;
  iban?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  chata?: T;
  title?: T;
  amount?: T;
  payer?: T;
  splitType?: T;
  weights?:
    | T
    | {
        participant?: T;
        weight?: T;
        id?: T;
      };
  createdAt?: T;
  note?: T;
  isPlanned?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prepayments_select".
 */
export interface PrepaymentsSelect<T extends boolean = true> {
  chata?: T;
  from?: T;
  amount?: T;
  note?: T;
  type?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backgrounds_select".
 */
export interface BackgroundsSelect<T extends boolean = true> {
  name?: T;
  isDefault?: T;
  type?: T;
  url?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  isDefault?: T;
  svg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}