/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    chatas: Chata;
    participants: Participant;
    expenses: Expense;
    prepayments: Prepayment;
    'joint-accounts': JointAccount;
    'claim-requests': ClaimRequest;
    'expense-attachments': ExpenseAttachment;
    backgrounds: Background;
    icons: Icon;
    users: User;
    media: Media;
    'data-requests': DataRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      participants: 'participants';
    };
  };
  collectionsSelect: {
    chatas: ChatasSelect<false> | ChatasSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    prepayments: PrepaymentsSelect<false> | PrepaymentsSelect<true>;
    'joint-accounts': JointAccountsSelect<false> | JointAccountsSelect<true>;
    'claim-requests': ClaimRequestsSelect<false> | ClaimRequestsSelect<true>;
    'expense-attachments': ExpenseAttachmentsSelect<false> | ExpenseAttachmentsSelect<true>;
    backgrounds: BackgroundsSelect<false> | BackgroundsSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'data-requests': DataRequestsSelect<false> | DataRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatas".
 */
export interface Chata {
  id: number;
  /**
   * Set this when the trip is fully settled. 12 months later the retention job deletes participants’ bank details and receipts of this chata. Leave empty while money is still moving.
   */
  settledAt?: string | null;
  /**
   * Full name of the chata/trip (e.g., "Chaloupka pod Medem")
   */
  name: string;
  /**
   * Short name used in QR codes and messages (e.g., "Chaloupka")
   */
  shortName: string;
  /**
   * Location description (e.g., "Beskydy")
   */
  location: string;
  /**
   * URL-friendly identifier for this chata
   */
  slug: string;
  /**
   * Domain names that should automatically load this chata
   */
  domains?:
    | {
        /**
         * Domain hostname (e.g., "trips.example.com")
         */
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Person managing the money for this trip. On a new chata the list is empty — save the chata, add participants (e.g. via "Prefill participants" above), then pick the banker. Everyone pays into the banker's own account, so their banking info is edited on the participant, not here.
   */
  banker?: (number | null) | Participant;
  /**
   * Background image (uses system default if not set)
   */
  background?: (number | null) | Background;
  /**
   * Icon (uses cottage icon if not set)
   */
  icon?: (number | null) | Icon;
  /**
   * Theme color (hex)
   */
  themeColor?: string | null;
  /**
   * Enable the information/details view for this trip
   */
  informationEnabled?: boolean | null;
  tripDateFrom?: string | null;
  tripDateTo?: string | null;
  /**
   * The dates above are only the window the trip will fall into. The frontend then shows the window and the planned number of nights instead of a fixed arrival and departure.
   */
  tripDatesTentative?: boolean | null;
  /**
   * How many nights the stay will take within the window.
   */
  tripPlannedNights?: number | null;
  /**
   * Check-in time (e.g., "od 15:00")
   */
  checkInTime?: string | null;
  /**
   * Check-out time (e.g., "do 10:00")
   */
  checkOutTime?: string | null;
  /**
   * Name of the accommodation (e.g., "Chaloupka pod Medem")
   */
  destinationName?: string | null;
  /**
   * Specific location (e.g., "Horní Lomná")
   */
  destinationLocation?: string | null;
  /**
   * Description of the destination
   */
  destinationDescription?: string | null;
  /**
   * Latitude — enables the weather forecast and the navigation button
   */
  destinationLat?: number | null;
  /**
   * Longitude
   */
  destinationLng?: number | null;
  /**
   * Useful links about the destination
   */
  destinationLinks?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Photos of the destination
   */
  photos?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Basic information bullets
   */
  basicInfo?:
    | {
        info: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What the place has (or is missing) — shown as ✓/✗ chips ("Na chatě je")
   */
  amenities?:
    | {
        /**
         * e.g., "Sauna", "Wi-Fi", "Povlečení"
         */
        name: string;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What to bring ("Co s sebou") — one bullet per item
   */
  packingItems?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Day-by-day plan; during the trip the current day is highlighted as "Today"
   */
  program?:
    | {
        date: string;
        /**
         * e.g., "Túra na Praděd (celý den, 18 km)"
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shops, pubs and trip tips around the place ("Okolí")
   */
  surroundings?:
    | {
        /**
         * e.g., "Potraviny Hruška — poslední obchod"
         */
        name: string;
        /**
         * Distance/opening hours (e.g., "400 m · po–so 7–17")
         */
        note?: string | null;
        category?: ('place' | 'trip') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Label + value rows ("Majitel — p. Novák · 605 112 233", "Noční klid — po 22:00")
   */
  contactRules?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wi-Fi password, where the keys are, door codes. Signed-in participants see the values; anonymous visitors only see that they exist.
   */
  privateInfo?:
    | {
        /**
         * e.g., "Wi-Fi". Labels are public, keep the secret in the value.
         */
        label: string;
        /**
         * e.g., "chata2024 (router in the hallway)"
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to the shared photo album. Offered before and during the trip so people add photos as they go, and featured again in the recap.
   */
  sharedAlbumUrl?: string | null;
  /**
   * Parking information
   */
  parking?: string | null;
  /**
   * Driving directions
   */
  carRoutes?:
    | {
        from: string;
        /**
         * e.g., "3:30"
         */
        duration: string;
        /**
         * e.g., "300 km"
         */
        distance: string;
        /**
         * Route description
         */
        route: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public transport options
   */
  publicTransportOptions?:
    | {
        /**
         * e.g., "Z Prahy"
         */
        title: string;
        /**
         * Day used by the "add to calendar" link: tam → arrival day, zpět → departure day
         */
        direction?: ('tam' | 'zpet') | null;
        /**
         * Participants travelling on this connection. Shown next to the cars in Organization and as a note on the route in Information.
         */
        riders?:
          | {
              participant: number | Participant;
              id?: string | null;
            }[]
          | null;
        /**
         * Total journey time
         */
        totalDuration?: string | null;
        /**
         * Additional notes
         */
        notes?: string | null;
        connections?:
          | {
              type: 'vlak' | 'autobus';
              /**
               * Train/bus number
               */
              number: string;
              from: string;
              to: string;
              /**
               * Format: HH:MM (e.g., "08:45")
               */
              departure: string;
              /**
               * Format: HH:MM (e.g., "12:30")
               */
              arrival: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable the bedroom organization view for this trip
   */
  bedroomOrganizationEnabled?: boolean | null;
  /**
   * Enable per-night occupancy tracking (requires trip dates)
   */
  advancedBedroomMode?: boolean | null;
  /**
   * Rooms available at this accommodation
   */
  rooms?:
    | {
        /**
         * Room name (e.g., "Pokoj u krbu", "Podkroví")
         */
        name: string;
        /**
         * Optional description of the room
         */
        description?: string | null;
        /**
         * Photo of the room
         */
        image?: (number | null) | Media;
        /**
         * Maximum number of people who can sleep in this room
         */
        maxSleepingSpaces: number;
        /**
         * Beds in this room
         */
        beds?:
          | {
              /**
               * Bed name/type (e.g., "Manželská postel", "Palanda - horní")
               */
              name: string;
              /**
               * Who sleeps in this bed
               */
              occupants?:
                | {
                    participant: number | Participant;
                    /**
                     * Which nights (1-indexed). Empty = all nights. E.g. [1, 2, 3]
                     */
                    nights?:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable the shared cars organization view for this trip
   */
  sharedCarsEnabled?: boolean | null;
  /**
   * Cars/rides for this trip
   */
  sharedCars?:
    | {
        /**
         * Car/trip name (e.g., "Auto tam - Petr", "Cesta zpět")
         */
        name: string;
        /**
         * Additional details about this ride (e.g., "Odjezd st 8:15 z Prahy-Chodova")
         */
        description?: string | null;
        /**
         * Total seats including the driver — enables the "4/5" occupancy badge and free-seat hints
         */
        seats?: number | null;
        /**
         * Who is driving this car
         */
        driver: number | Participant;
        /**
         * Front-seat passenger
         */
        frontPassenger?: (number | null) | Participant;
        /**
         * Other passengers
         */
        passengers?:
          | {
              participant: number | Participant;
              id?: string | null;
            }[]
          | null;
        /**
         * Equipment/cargo in the car
         */
        equipment?:
          | {
              /**
               * Equipment name (e.g., "Pivo", "Kufry")
               */
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  /**
   * Participant's full name
   */
  name: string;
  /**
   * Name in the accusative case, e.g. "Katku" — used in phrases like "Vojta zve Katku". Falls back to the plain name when empty.
   */
  akuzativ?: string | null;
  /**
   * Name in the vocative case, e.g. "Katko" — stored for future greetings, not displayed anywhere yet.
   */
  vokativ?: string | null;
  /**
   * The trip/chata this participant belongs to
   */
  chata: number | Chata;
  /**
   * Participant is travelling with a pet
   */
  hasPet?: boolean | null;
  /**
   * This participant's expense shares are permanently covered by another participant (e.g. a child paid by a parent). New expenses automatically get a standing invitation; use the button below to apply the SAVED value to existing expenses.
   */
  paidBy?: (number | null) | Participant;
  /**
   * Account number in Czech format (e.g., "123456/0100") - only needed for creditors
   */
  accountNumber?: string | null;
  /**
   * Full IBAN for QR code generation - only needed for creditors
   */
  iban?: string | null;
  /**
   * User account linked to this participant ("účet"). Use the button below to create a new account from an email — nothing is emailed until the person requests a login link themselves.
   */
  account?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Full display name shown on the frontend (e.g. "Kateřina Rechová")
   */
  name?: string | null;
  /**
   * First name in the vocative case, e.g. "Katko" — used for the personal greeting ("Ahoj, Katko."). Falls back to the participant/account name.
   */
  vokativ?: string | null;
  /**
   * Superadmins manage everything; admins manage only their assigned chatas; users sign in on the frontend and see their own participant finances.
   */
  role: 'superadmin' | 'admin' | 'user';
  /**
   * Chatas this admin can manage (only applies to the admin role)
   */
  assignedChatas?: (number | Chata)[] | null;
  /**
   * Participants this account is linked to (one per chata)
   */
  participants?: {
    docs?: (number | Participant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Set on every successful login. Participants linked to this account are hidden from anonymous visitors only after the first login.
   */
  lastLoginAt?: string | null;
  loginToken?: string | null;
  loginTokenExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backgrounds".
 */
export interface Background {
  id: number;
  /**
   * Display name for this background
   */
  name: string;
  /**
   * System default - cannot be deleted
   */
  isDefault?: boolean | null;
  type: 'url' | 'upload';
  /**
   * Image URL. An external http(s) image is downloaded on save and stored in the site’s own storage (the row switches to "Uploaded Image"); a relative URL (e.g. /bg/…) is served as-is.
   */
  url?: string | null;
  /**
   * Upload a background image
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Files backing Backgrounds and Icons (not expense receipts)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  /**
   * Display name for this icon
   */
  name: string;
  /**
   * System default - cannot be deleted
   */
  isDefault?: boolean | null;
  /**
   * Upload an SVG icon file
   */
  svg: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  /**
   * The trip/chata this expense belongs to
   */
  chata: number | Chata;
  /**
   * Description of the expense
   */
  title: string;
  /**
   * Total amount (use negative values for refunds)
   */
  amount: number;
  /**
   * Who paid for this expense (a participant or a joint account)
   */
  payer?:
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'joint-accounts';
        value: number | JointAccount;
      } | null);
  /**
   * How to split this expense among participants
   */
  splitType: 'equal' | 'weighted';
  /**
   * Weighted distribution - only used when Split Type is "Weighted"
   */
  weights?:
    | {
        /**
         * Participant sharing this expense
         */
        participant: number | Participant;
        /**
         * Weight multiplier for this participant (e.g., 1, 0.5, 2). If all weights add up to the total amount (±1 Kč), they are displayed as Kč amounts.
         */
        weight: number;
        id?: string | null;
      }[]
    | null;
  /**
   * The host pays the guest's share of this expense. A host can invite multiple guests; each guest can be invited only once per expense.
   */
  invitations?:
    | {
        /**
         * Who covers the share (the inviter)
         */
        host: number | Participant;
        /**
         * Whose share is covered (the invited one)
         */
        guest: number | Participant;
        /**
         * Standing arrangement (e.g. a parent paying for a child) - managed automatically from the participant's "Paid By" field and hidden on the expense card. Leave unchecked for one-off invitations, which are shown.
         */
        auto?: boolean | null;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  /**
   * Optional notes about this expense
   */
  note?: string | null;
  /**
   * Receipts and other attachments (photos, PDF) - on mobile the file picker offers taking a photo directly
   */
  attachments?: (number | ExpenseAttachment)[] | null;
  /**
   * Account that created this expense (set automatically). Frontend users may edit/delete only their own expenses.
   */
  authoredBy?: (number | null) | User;
  /**
   * Account of the paying participant (set automatically). They may confirm and edit this expense.
   */
  payerAccount?: (number | null) | User;
  /**
   * Expenses recorded by a participant for SOMEBODY ELSE wait for the payer (if they have an account) or the banker. Anything but "Approved" is hidden from the site and left out of all balances.
   */
  approvalStatus?: ('approved' | 'pending' | 'rejected') | null;
  /**
   * Why it was rejected — emailed to the author
   */
  approvalNote?: string | null;
  /**
   * Who confirmed or rejected the expense
   */
  approvalDecidedBy?: (number | null) | User;
  approvalDecidedAt?: string | null;
  /**
   * Planned expense (not yet paid) - uncheck when actually paid
   */
  isPlanned?: boolean | null;
  updatedAt: string;
}
/**
 * Shared bank accounts ("společný účet") of 2+ participants. Can be selected as the payer of an expense or sender of a prepayment; the amount is attributed equally to the members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "joint-accounts".
 */
export interface JointAccount {
  id: number;
  /**
   * Display name of the joint account (e.g., "Alice + Bob")
   */
  name: string;
  /**
   * The trip/chata this joint account belongs to
   */
  chata: number | Chata;
  /**
   * Participants sharing this account (at least 2)
   */
  members?: (number | Participant)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Receipts and other expense attachments (photos, PDF)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-attachments".
 */
export interface ExpenseAttachment {
  id: number;
  /**
   * Optional description of the attachment
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prepayments".
 */
export interface Prepayment {
  id: number;
  /**
   * The trip/chata this prepayment belongs to
   */
  chata: number | Chata;
  /**
   * Who sent the payment (or who received it if negative) — a participant or a joint account
   */
  from?:
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'joint-accounts';
        value: number | JointAccount;
      } | null);
  /**
   * Amount (positive = to banker, negative = from banker/refund)
   */
  amount: number;
  /**
   * Description (e.g., "Záloha", "Doplatek", "Distribuce")
   */
  note?: string | null;
  /**
   * Type of prepayment
   */
  type: 'advance' | 'supplement' | 'refund' | 'distribution';
  createdAt: string;
  updatedAt: string;
}
/**
 * Requests to link a participant to a frontend account ("žádosti o propojení"). Approve by setting status to approved — that links the participant, rejects rival claims and emails the requester. Rejections require a reason (it is emailed).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-requests".
 */
export interface ClaimRequest {
  id: number;
  /**
   * The participant being claimed
   */
  participant: number | Participant;
  /**
   * Derived from the participant — drives admin-scoped access
   */
  chata?: (number | null) | Chata;
  /**
   * The account that claims to be this participant
   */
  user: number | User;
  /**
   * Approving links the participant to the account and auto-rejects rival claims; rejecting requires a reason (emailed to the requester).
   */
  status: 'pending' | 'approved' | 'rejected' | 'cancelled';
  /**
   * Rejection reason — emailed to the requester
   */
  reason?: string | null;
  /**
   * Admin who decided (empty for auto-approvals)
   */
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  /**
   * Approved without an admin ("známá tvář" — linked participant in another chata)
   */
  autoApproved?: boolean | null;
  /**
   * When the 3-day reminder went out to admins
   */
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log of GDPR data-subject requests (access, copy, rectification, erasure...). One row per request; the policy promises an answer within one month of receivedAt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests".
 */
export interface DataRequest {
  id: number;
  /**
   * Name or email of the person making the request
   */
  subject: string;
  type: 'access' | 'rectification' | 'erasure' | 'restriction' | 'portability' | 'objection' | 'other';
  receivedAt: string;
  status: 'received' | 'in-progress' | 'done' | 'refused';
  resolvedAt?: string | null;
  /**
   * How the request was verified and handled (export sent, anonymized, refused and why...)
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'chatas';
        value: number | Chata;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'prepayments';
        value: number | Prepayment;
      } | null)
    | ({
        relationTo: 'joint-accounts';
        value: number | JointAccount;
      } | null)
    | ({
        relationTo: 'claim-requests';
        value: number | ClaimRequest;
      } | null)
    | ({
        relationTo: 'expense-attachments';
        value: number | ExpenseAttachment;
      } | null)
    | ({
        relationTo: 'backgrounds';
        value: number | Background;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'data-requests';
        value: number | DataRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatas_select".
 */
export interface ChatasSelect<T extends boolean = true> {
  settledAt?: T;
  name?: T;
  shortName?: T;
  location?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  banker?: T;
  background?: T;
  icon?: T;
  themeColor?: T;
  informationEnabled?: T;
  tripDateFrom?: T;
  tripDateTo?: T;
  tripDatesTentative?: T;
  tripPlannedNights?: T;
  checkInTime?: T;
  checkOutTime?: T;
  destinationName?: T;
  destinationLocation?: T;
  destinationDescription?: T;
  destinationLat?: T;
  destinationLng?: T;
  destinationLinks?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  basicInfo?:
    | T
    | {
        info?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        available?: T;
        id?: T;
      };
  packingItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  program?:
    | T
    | {
        date?: T;
        description?: T;
        id?: T;
      };
  surroundings?:
    | T
    | {
        name?: T;
        note?: T;
        category?: T;
        id?: T;
      };
  contactRules?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  privateInfo?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  sharedAlbumUrl?: T;
  parking?: T;
  carRoutes?:
    | T
    | {
        from?: T;
        duration?: T;
        distance?: T;
        route?: T;
        id?: T;
      };
  publicTransportOptions?:
    | T
    | {
        title?: T;
        direction?: T;
        riders?:
          | T
          | {
              participant?: T;
              id?: T;
            };
        totalDuration?: T;
        notes?: T;
        connections?:
          | T
          | {
              type?: T;
              number?: T;
              from?: T;
              to?: T;
              departure?: T;
              arrival?: T;
              id?: T;
            };
        id?: T;
      };
  bedroomOrganizationEnabled?: T;
  advancedBedroomMode?: T;
  rooms?:
    | T
    | {
        name?: T;
        description?: T;
        image?: T;
        maxSleepingSpaces?: T;
        beds?:
          | T
          | {
              name?: T;
              occupants?:
                | T
                | {
                    participant?: T;
                    nights?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  sharedCarsEnabled?: T;
  sharedCars?:
    | T
    | {
        name?: T;
        description?: T;
        seats?: T;
        driver?: T;
        frontPassenger?: T;
        passengers?:
          | T
          | {
              participant?: T;
              id?: T;
            };
        equipment?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  akuzativ?: T;
  vokativ?: T;
  chata?: T;
  hasPet?: T;
  paidBy?: T;
  accountNumber?: T;
  iban?: T;
  account?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  chata?: T;
  title?: T;
  amount?: T;
  payer?: T;
  splitType?: T;
  weights?:
    | T
    | {
        participant?: T;
        weight?: T;
        id?: T;
      };
  invitations?:
    | T
    | {
        host?: T;
        guest?: T;
        auto?: T;
        id?: T;
      };
  createdAt?: T;
  note?: T;
  attachments?: T;
  authoredBy?: T;
  payerAccount?: T;
  approvalStatus?: T;
  approvalNote?: T;
  approvalDecidedBy?: T;
  approvalDecidedAt?: T;
  isPlanned?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prepayments_select".
 */
export interface PrepaymentsSelect<T extends boolean = true> {
  chata?: T;
  from?: T;
  amount?: T;
  note?: T;
  type?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "joint-accounts_select".
 */
export interface JointAccountsSelect<T extends boolean = true> {
  name?: T;
  chata?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-requests_select".
 */
export interface ClaimRequestsSelect<T extends boolean = true> {
  participant?: T;
  chata?: T;
  user?: T;
  status?: T;
  reason?: T;
  decidedBy?: T;
  decidedAt?: T;
  autoApproved?: T;
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-attachments_select".
 */
export interface ExpenseAttachmentsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backgrounds_select".
 */
export interface BackgroundsSelect<T extends boolean = true> {
  name?: T;
  isDefault?: T;
  type?: T;
  url?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  isDefault?: T;
  svg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  vokativ?: T;
  role?: T;
  assignedChatas?: T;
  participants?: T;
  lastLoginAt?: T;
  loginToken?: T;
  loginTokenExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests_select".
 */
export interface DataRequestsSelect<T extends boolean = true> {
  subject?: T;
  type?: T;
  receivedAt?: T;
  status?: T;
  resolvedAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}